name: homestay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  pocketbase: ^0.18.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  http: ^1.3.0
  image_picker: ^1.0.7
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
